// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6PjT8QPlbY6oYBtXskN4HUDCSlM0JRiw',
    appId: '1:1022671391777:web:3e1240cb064bfa6ef72760',
    messagingSenderId: '1022671391777',
    projectId: 'cabanas-app',
    authDomain: 'cabanas-app.firebaseapp.com',
    storageBucket: 'cabanas-app.firebasestorage.app',
    measurementId: 'G-T5LDB8VGBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnOYWyT3F_rDFfPRC73AVXSLFJ05Ivrrw',
    appId: '1:1022671391777:android:14fef10caf7b4473f72760',
    messagingSenderId: '1022671391777',
    projectId: 'cabanas-app',
    storageBucket: 'cabanas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWE5M45TuMNUbyVskOC-EPN9X8H186lw',
    appId: '1:1022671391777:ios:f2932db899d12fe0f72760',
    messagingSenderId: '1022671391777',
    projectId: 'cabanas-app',
    storageBucket: 'cabanas-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzWE5M45TuMNUbyVskOC-EPN9X8H186lw',
    appId: '1:1022671391777:ios:f2932db899d12fe0f72760',
    messagingSenderId: '1022671391777',
    projectId: 'cabanas-app',
    storageBucket: 'cabanas-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6PjT8QPlbY6oYBtXskN4HUDCSlM0JRiw',
    appId: '1:1022671391777:web:aa2af3c403ed0b1bf72760',
    messagingSenderId: '1022671391777',
    projectId: 'cabanas-app',
    authDomain: 'cabanas-app.firebaseapp.com',
    storageBucket: 'cabanas-app.firebasestorage.app',
    measurementId: 'G-MPTBQPHDLD',
  );
}
